import FileTypes from '@/utils/fileTypes'
import { writeFile } from '@/utils'

const writeConfig = (dir = process.cwd(), format = FileTypes.JSON_NO_EXT, overwrite) => {
    // We require it here only, making sure tsconfig is generated by now in case the user wants TypeScript
    return writeFile(dir, '.eslintrc', require('./'), format, overwrite)
}

export default writeConfig
