process.env.MHY_UI_ACTION = 'action'
process.env.MHY_UI_ACTION_CLEAR = 'clear'
process.env.MHY_UI_ACTION_DATA = 'data'
process.env.MHY_UI_ACTION_UPDATE = 'update'
process.env.MHY_UI_ACTION_FUNCTION = 'function'
